# Generated by Django 3.1.4 on 2020-12-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201211_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
