version: "3.9"

services:
  api:
    image: app
    container_name: api-book-site
    command: python manage.py runserver 0.0.0.0:8000
    environment: &environment
      DEBUG: ${DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - django_migration

  django_migration:
    build: .
    image: app
    container_name: djagno-migrations
    command: python manage.py migrate
    environment: *environment
    volumes:
      - .:/app
    depends_on:
      - api_db

  api_db:
    image: postgres:latest
    container_name: api-postgres
    restart: unless-stopped
    volumes:
      - postgres_api:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_api:
